// revision-history-for-angular/src/app/menu/menu.component.ts
/**
 * @license Copyright (c) 2003-2024, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md.
 */

import { Component } from '@angular/core';

@Component( {
	selector: 'menu',
	templateUrl: './menu.component.html',
	styleUrls: [ './menu.component.css' ]
} )

export class MenuComponent {}

<h1>Revision history for Angular</h1>
<nav>
  <ul>
    <li>
      <a routerLink="/load-save-integration">Load and save integration</a>
    </li>
    <li>
      <a routerLink="/revision-history-adapter">Revision history adapter</a>
    </li>
  </ul>
</nav>

// revision-history-for-react/src/components/Menu.js
/**
 * @license Copyright (c) 2003-2024, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md.
 */

import React from 'react';
import { Link } from 'react-router-dom';

const Menu = () => {
	return (
		<div>
			<h1>Revision history for React</h1>
			<nav>
				<ul>
					<li><Link to="/load-save-integration">Load save integration</Link></li>
					<li><Link to="/revision-history-adapter">Revision history adapter</Link></li>
				</ul>
			</nav>
		</div>
	);
};

export default Menu;
