// revision-history-for-angular/src/main.ts
/**
 * @license Copyright (c) 2003-2024, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md.
 */

import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if ( environment.production ) {
	enableProdMode();
}

platformBrowserDynamic().bootstrapModule( AppModule )
	.catch( err => console.error( err ) );

// real-time-collaboration-editor-multi-root-for-react/src/main.jsx
/**
 * @license Copyright (c) 2003-2025, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md.
 */

import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

ReactDOM.createRoot( document.getElementById( 'app' ) ).render(
	<React.StrictMode>
		<App />
	</React.StrictMode>
);
