// real-time-collaboration-for-vue/src/app.vue
<!--
    Copyright (c) 2003-2021, CKSource - Frederico Knabben. All rights reserved.
    This file is licensed under the terms of the MIT License (see LICENSE.md).
-->

<template>
	<div id="app">
		<configuration-dialog v-if=" !configuration " :onSubmit=" handleUpdate " />
		<sample v-else :configuration=" configuration " />
	</div>
</template>

<script>
import ConfigurationDialog from './components/configuration-dialog';
import Sample from './components/sample';

export default {
	name: 'app',
	components: { ConfigurationDialog, Sample },
	data() {
		return {
			configuration: null
		};
	},
	methods: {
		handleUpdate( configuration ) {
			this.configuration = configuration;
		}
	}
};
</script>

// real-time-collaboration-for-react/src/app.js
/**
 * @license Copyright (c) 2003-2021, CKSource - Frederico Knabben. All rights reserved.
 * This file is licensed under the terms of the MIT License (see LICENSE.md).
 */

import React, { Component } from 'react';
import ConfigurationDialog from './configuration-dialog';
import Sample from './sample';

export default class App extends Component {
	state = {
		configuration: null
	};

	render() {
		// Configuration data needed to initialize the editor is available only after the configuration dialog
		// is submitted, hence the editor is initialized after ConfigurationDialog returns the configuration.
		if ( !this.state.configuration ) {
			return <ConfigurationDialog onSubmit={ configuration => this.setState( { configuration } ) } />;
		}

		return <Sample configuration={ this.state.configuration } />;
	}
}
