// real-time-collaboration-for-vue/src/components/configuration-dialog.vue
<!--
    Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
    This file is licensed under the terms of the MIT License (see LICENSE.md).
-->
<template>
	<div id="overlay" :class="{ warning: isWarning }">
		<form class="body" @submit="evt => handleSubmit( evt )">
			<h2>Connect CKEditor Cloud Services</h2>
			<p>
				If you do not have Cloud Services URLs yet,&nbsp;
				<a href="https://ckeditor.com/docs/cs/latest/guides/collaboration/quick-start.html" target="_blank" rel="noopener noreferrer">see the documentation</a>.
			</p>
			<div>
				<label for="upload-url">Upload URL</label>
				<input
					name="upload-url"
					id="upload-url"
					@change="evt => handleConfigChange( evt.target.value, 'uploadUrl' )"
					:value="config.uploadUrl"
				/>
			</div>
			<div>
				<label for="web-socket-url">WebSocket URL</label>
				<input
					name="web-socket-url"
					id="web-socket-url"
					@change="evt => handleConfigChange( evt.target.value, 'webSocketUrl' )"
					:value="config.webSocketUrl" />
			</div>
			<div>
				<label for="token-url">Token URL</label>
				<input
					required
					name="token-url"
					id="token-url"
					@input="evt => handleTokenUrlChange( evt.target.value )"
					:value="config.tokenUrl" />
			</div>
			<div id="additional" :class="{ visible: isCloudServicesTokenEndpoint( config.tokenUrl ) }">
				<p>Use one of the following users to define the user data.</p>
				<div id="user-container">
					<div
						v-for="user in users"
						:key="user.id"
						@click="() => selectUser( user )"
						:class="{ active: selectedUser == user.id }"
						>
						<img v-if="user.avatar" alt="" :src="user.avatar">
						<span v-if="!user.avatar && user.name" class="pseudo-avatar">{{ getUserInitials( user.name ) }}</span>
						<span v-if="!user.avatar && !user.name" class="pseudo-avatar anonymous"></span>
						{{ user.name || '(anonymous)' }}
						<span class="role">{{ user.role }}</span>
					</div>
				</div>
			</div>
			<div>
				<label for="document-id">Document ID</label>
				<input
					name="document-id"
					id="document-id"
					required
					@change="evt => this.documentId = evt.target.value"
					:value="documentId" />
			</div>
			<button id="start">Start</button>
		</form>
	</div>
</template>

<script>
export default {
	name: 'configuration-dialog',
	props: [ 'onSubmit' ],
	data() {
		return {
			LOCAL_STORAGE_KEY: 'CKEDITOR_CS_CONFIG',
			users: [
				{
					id: 'e1',
					name: 'Tom Rowling',
					avatar: 'https://randomuser.me/api/portraits/men/30.jpg',
					role: 'writer'
				},
				{
					id: 'e2',
					name: 'Wei Hong',
					avatar: 'https://randomuser.me/api/portraits/women/51.jpg',
					role: 'writer'
				},
				{
					id: 'e3',
					name: 'Rani Patel',
					role: 'writer'
				},
				{
					id: 'e4',
					name: 'Henrik Jensen',
					role: 'commentator'
				},
				{
					id: this.randomString(),
					role: 'writer'
				},
				{
					id: this.randomString(),
					role: 'reader'
				}
			],
			config: null,
			documentId: this.handleDocIdInUrl(),
			selectedUser: null,
			isWarning: false
		};
	},
	created() {
		this.config = this.getStoredConfig();
	},
	methods: {
		handleConfigChange( value, property ) {
			const config = this.config;

			config[ property ] = value;

			this.config = config;
		},

		handleTokenUrlChange( value ) {
			this.handleConfigChange( value, 'tokenUrl' );
			this.selectedUser = null;
			this.isWarning = false;
		},

		selectUser( data ) {
			this.selectedUser = data.id;
			this.isWarning = false;

			const config = this.config;

			config.tokenUrl = `${ this.getRawTokenUrl( config.tokenUrl ) }?` + Object.keys( data )
				.filter( key => data[ key ] )
				.map( key => {
					if ( key === 'role' ) {
						return `${ key }=${ data[ key ] }`;
					}

					return `user.${ key }=${ data[ key ] }`;
				} )
				.join( '&' );

			this.config = config;
		},

		handleSubmit( evt ) {
			evt.preventDefault();

			const { config, documentId } = this;

			if ( this.isCloudServicesTokenEndpoint( config.tokenUrl ) && !config.tokenUrl.includes( '?' ) ) {
				this.isWarning = true;

				return;
			}

			this.storeConfig( Object.assign( {}, config, { tokenUrl: this.getRawTokenUrl( config.tokenUrl ) } ) );
			this.updateDocIdInUrl( documentId );
			this.onSubmit( Object.assign( {}, config, { documentId } ) );
		},

		getUserInitials( name ) {
			return name.split( ' ', 2 ).map( part => part.charAt( 0 ) ).join( '' ).toUpperCase();
		},

		handleDocIdInUrl() {
			let id = this.getDocIdFromUrl();

			if ( !id ) {
				id = this.randomString();
				this.updateDocIdInUrl( id );
			}

			return id;
		},

		updateDocIdInUrl( id ) {
			window.history.replaceState( {}, document.title, this.generateUrlWithDocId( id ) );
		},

		generateUrlWithDocId( id ) {
			return `${ window.location.href.split( '?' )[ 0 ] }?docId=${ id }`;
		},

		getDocIdFromUrl() {
			const docIdMatch = location.search.match( /docId=(.+)$/ );

			return docIdMatch ? decodeURIComponent( docIdMatch[ 1 ] ) : null;
		},

		isCloudServicesTokenEndpoint( tokenUrl ) {
			return /cke-cs[\w-]*\.com\/token\/dev/.test( tokenUrl );
		},

		getRawTokenUrl( url ) {
			if ( this.isCloudServicesTokenEndpoint( url ) ) {
				return url.split( '?' )[ 0 ];
			}

			return url;
		},

		randomString() {
			return Math.floor( Math.random() * Math.pow( 2, 52 ) ).toString( 32 );
		},

		storeConfig( csConfig ) {
			localStorage.setItem( this.LOCAL_STORAGE_KEY, JSON.stringify( csConfig ) );
		},

		getStoredConfig() {
			const config = JSON.parse( localStorage.getItem( this.LOCAL_STORAGE_KEY ) || '{}' );
			return {
				tokenUrl: config.tokenUrl || '',
				uploadUrl: config.uploadUrl || '',
				webSocketUrl: config.webSocketUrl || ''
			};
		}
	}
};
</script>

<style scoped>
	* {
		box-sizing: border-box;
	}

	body,
	html {
		margin: 0;
	}

	#overlay {
		font-family: Helvetica;
		width: 100%;
		height: 100%;
		position: fixed;
		top: 0;
		bottom: 0;
		left: 0;
		background: #333;
		display: flex;
		flex-direction: column;
		align-items: center;
		padding: 4vh 4vw;
		overflow: auto;
	}

	#overlay.hidden {
		display: none;
	}

	#overlay .body {
		font-size: 14px;
		width: 100%;
		max-width: 800px;
		background: white;
		padding: 40px;
		border-radius: 3px;
		box-shadow: 0 0 15px 5px #000
	}

	#overlay h2 {
		margin-top: 0;
		text-align: center;
	}

	#overlay p {
		text-align: center;
		margin-bottom: 1.5em;
		width: 100%;
	}

	#overlay a {
		color: hsl(219, 100%, 50%);
		text-decoration: none;
	}

	#overlay a:hover {
		text-decoration: underline;
	}

	#overlay .body>div {
		display: flex;
		align-items: center;
		margin: 15px 0;
	}

	#overlay .body>div label {
		width: 180px;
		font-weight: bold;
	}

	#overlay .body>div input {
		width: 100%;
		padding: 8px;
		font-size: 1em;
	}

	button#start {
		display: block;
		width: 100%;
		max-width: 300px;
		margin: 20px auto 0;
		padding: 15px;
		background: hsl(104, 44%, 48%);
		color: white;
		font-weight: bold;
		border: 0;
		border-radius: 3px;
		font-size: 1em;
		cursor: pointer;
		transition: 250ms ease background;
	}

	button#start:hover {
		background: hsl(104, 44%, 41%);
	}

	#overlay #additional {
		display: none;
		flex-wrap: wrap;
	}

	#overlay #additional.visible {
		display: flex;
	}

	#overlay.warning #additional > p {
		color: red;
	}

	#overlay.warning #user-container {
		border-color: red;
	}

	#overlay #user-container {
		width: 100%;
		border: 1px solid hsl(0, 0%, 85%);
	}
	#overlay #user-container div {
		display: flex;
		cursor: pointer;
		align-items: center;
		height: 48px;
		padding: 10px;
		background: hsl(0, 0%, 97%);
		transition: 250ms ease background;
	}
	#overlay #user-container div:nth-child( odd ) {
		background: #fff;
	}
	#overlay #user-container div:hover {
		background: hsl(0, 0%, 92%);
	}

	#overlay #user-container div.active {
		background: hsl(133, 50%, 84%);
	}

	#overlay #user-container img,
	#overlay #user-container .pseudo-avatar {
		width: 32px;
		height: 32px;
		border-radius: 50%;
		border: 2px solid var(--ck-user-avatar-background);
		margin-right: 10px;
		background: var(--ck-user-avatar-color);
	}
	#overlay #user-container .pseudo-avatar {
		font-size: 0.9em;
		text-align: center;
		line-height: 30px;
		background: var(--ck-user-avatar-background);
		color: var(--ck-user-avatar-color);
	}
	#overlay #user-container .pseudo-avatar.anonymous {
		background-image: url(data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2020%2020%22%3E%0A%20%20%3Cpath%20fill%3D%22%23FFF%22%20fill-rule%3D%22nonzero%22%20d%3D%22M9.8%2020H2c0-5.7%205-5.7%206-7l.2-.8c-1.6-.8-2.7-2.7-2.7-5%200-2.8%202-5.2%204.3-5.2S14%204.4%2014%207.3c0%202.2-1%204-2.6%205l.2.6c1.2%201.3%206%201.4%206%207H9.8z%22%2F%3E%0A%3C%2Fsvg%3E)
	}

	.role {
		font-size: 11px;
		border: 1px solid #3570aa;
		border-radius: 4px;
		color: #3570aa;
		padding: 2px 5px;
		margin-left: 10px;
		font-weight: bold;
		margin-top: 2px;
	}
</style>

// real-time-collaboration-for-react/src/configuration-dialog.js
/**
 * @license Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 * This file is licensed under the terms of the MIT License (see LICENSE.md).
 */

import React, { Component } from 'react';
import './configuration-dialog.css';

const LOCAL_STORAGE_KEY = 'CKEDITOR_CS_CONFIG';

const users = [
	{
		id: 'e1',
		name: 'Tom Rowling',
		avatar: 'https://randomuser.me/api/portraits/men/30.jpg',
		role: 'writer'
	},
	{
		id: 'e2',
		name: 'Wei Hong',
		avatar: 'https://randomuser.me/api/portraits/women/51.jpg',
		role: 'writer'
	},
	{
		id: 'e3',
		name: 'Rani Patel',
		role: 'writer'
	},
	{
		id: 'e4',
		name: 'Henrik Jensen',
		role: 'commentator'
	},
	{
		id: randomString(),
		role: 'writer'
	},
	{
		id: randomString(),
		role: 'reader'
	}
];

export default class ConfigurationPage extends Component {
	state = {
		config: getStoredConfig(),
		documentId: handleDocIdInUrl(),
		selectedUser: null,
		isWarning: false
	};

	handleConfigChange( value, property ) {
		const config = this.state.config;

		config[ property ] = value;

		this.setState( { config } );
	}

	handleTokenUrlChange( value ) {
		this.handleConfigChange( value, 'tokenUrl' );
		this.setState( {
			selectedUser: null,
			isWarning: false
		} );
	}

	selectUser( data ) {
		this.setState( {
			selectedUser: data.id,
			isWarning: false
		} );

		const config = this.state.config;

		config.tokenUrl = `${ getRawTokenUrl( config.tokenUrl ) }?` + Object.keys( data )
			.filter( key => data[ key ] )
			.map( key => {
				if ( key === 'role' ) {
					return `${ key }=${ data[ key ] }`;
				}

				return `user.${ key }=${ data[ key ] }`;
			} )
			.join( '&' );

		this.setState( { config } );
	}

	handleSubmit( evt ) {
		evt.preventDefault();

		const { config, documentId } = this.state;
		const { onSubmit } = this.props;

		if ( isCloudServicesTokenEndpoint( config.tokenUrl ) && !config.tokenUrl.includes( '?' ) ) {
			this.setState( { isWarning: true } );

			return;
		}

		storeConfig( Object.assign( {}, config, { tokenUrl: getRawTokenUrl( config.tokenUrl ) } ) );
		updateDocIdInUrl( documentId );
		onSubmit( Object.assign( {}, config, { documentId } ) );
	}

	render() {
		const { config, documentId, selectedUser, isWarning } = this.state;

		return (
			<div id="overlay" className={ isWarning ? ' warning' : '' }>
				<form className="body" onSubmit={ evt => this.handleSubmit( evt ) }>
					<h2>Connect CKEditor Cloud Services</h2>
					<p>
						If you do not have Cloud Services URLs yet,&nbsp;
						<a href="https://ckeditor.com/docs/cs/latest/guides/collaboration/quick-start.html"
							target="_blank" rel="noopener noreferrer">
							see the documentation
						</a>.
					</p>
					<div>
						<label htmlFor="upload-url">Upload URL</label>
						<input
							name="upload-url"
							onChange={ evt => this.handleConfigChange( evt.target.value, 'uploadUrl' ) }
							value={ config.uploadUrl } />
					</div>
					<div>
						<label htmlFor="web-socket-url">WebSocket URL</label>
						<input
							name="web-socket-url"
							onChange={ evt => this.handleConfigChange( evt.target.value, 'webSocketUrl' ) }
							value={ config.webSocketUrl } />
					</div>
					<div>
						<label htmlFor="token-url">Token URL</label>
						<input
							required
							name="token-url"
							onChange={ evt => this.handleTokenUrlChange( evt.target.value ) }
							value={ config.tokenUrl } />
					</div>

					<div id="additional" className={ isCloudServicesTokenEndpoint( config.tokenUrl ) ? 'visible' : '' }>
						<p>Use one of the following users to define the user data.</p>
						<div id="user-container">
							{ users.map( data => {
								return (
									<div
										key={ data.id }
										onClick={ () => this.selectUser( data ) }
										className={ selectedUser == data.id ? 'active' : '' }
									>
										{ data.avatar && <img src={ data.avatar } /> }
										{ !data.avatar && data.name && <span className="pseudo-avatar">{ getUserInitials( data.name ) }</span> }
										{ !data.avatar && !data.name && <span className="pseudo-avatar anonymous"></span> }
										{ data.name || '(anonymous)' }
										<span className="role">{ data.role }</span>
									</div>
								);
							} ) }
						</div>
					</div>

					<div>
						<label htmlFor="document-id">Document ID</label>
						<input name="document-id" required defaultValue={ documentId } />
					</div>

					<button id="start">Start</button>
				</form>
			</div>
		);
	}
}

function getUserInitials( name ) {
	return name.split( ' ', 2 ).map( part => part.charAt( 0 ) ).join( '' ).toUpperCase();
}

function handleDocIdInUrl() {
	let id = getDocIdFromUrl();

	if ( !id ) {
		id = randomString();
		updateDocIdInUrl( id );
	}

	return id;
}

function updateDocIdInUrl( id ) {
	window.history.replaceState( {}, document.title, generateUrlWithDocId( id ) );
}

function generateUrlWithDocId( id ) {
	return `${ window.location.href.split( '?' )[ 0 ] }?docId=${ id }`;
}

function getDocIdFromUrl() {
	const docIdMatch = location.search.match( /docId=(.+)$/ );

	return docIdMatch ? decodeURIComponent( docIdMatch[ 1 ] ) : null;
}

function isCloudServicesTokenEndpoint( tokenUrl ) {
	return /cke-cs[\w-]*\.com\/token\/dev/.test( tokenUrl );
}

function getRawTokenUrl( url ) {
	if ( isCloudServicesTokenEndpoint( url ) ) {
		return url.split( '?' )[ 0 ];
	}

	return url;
}

function randomString() {
	return Math.floor( Math.random() * Math.pow( 2, 52 ) ).toString( 32 );
}

function storeConfig( csConfig ) {
	localStorage.setItem( LOCAL_STORAGE_KEY, JSON.stringify( csConfig ) );
}

function getStoredConfig() {
	const config = JSON.parse( localStorage.getItem( LOCAL_STORAGE_KEY ) || '{}' );

	return {
		tokenUrl: config.tokenUrl || '',
		uploadUrl: config.uploadUrl || '',
		webSocketUrl: config.webSocketUrl || ''
	};
}
